begin;
do $$
declare u uuid:=gen_random_uuid();sid uuid:=gen_random_uuid();town public.ssl_locations;team public.ssl_teams;logo text:='1/'||gen_random_uuid()::text||'.png';v integer;
begin
 insert into auth.users(id,email) values(u,'team_test_'||substr(replace(u::text,'-',''),1,8)||'@accounts.supasports.invalid');
 insert into auth.sessions(id,user_id,created_at,updated_at) values(sid,u,now(),now());
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated','session_id',sid)::text,true);
 begin perform public.save_ssl_location(null,'Forbidden test','',true);raise exception 'Participant managed locations';exception when others then if sqlerrm<>'Commissioner access required' then raise;end if;end;
 if public.can_upload_ssl_logo(logo) then raise exception 'Participant logo upload allowed';end if;
 insert into league_private.session_access(session_id,user_id,slot,code_version) select sid,u,0,version from league_private.access_codes where slot=0;
 set local role authenticated;
 select * into town from public.save_ssl_location(null,'Hometown regression '||u::text,'Temporary fixture',true);
 insert into storage.objects(bucket_id,name,metadata) values('ssl-team-logos',logo,'{"mimetype":"image/png","size":100}');
 select * into team from public.save_ssl_team(1,'Test Pirates '||u::text,town.id,logo);
 if team.location_id<>town.id or team.logo_path<>logo then raise exception 'Team identity not saved';end if;
 if has_table_privilege('authenticated','public.ssl_teams','UPDATE') or has_function_privilege('anon','public.save_ssl_team(integer,text,uuid,text)','EXECUTE') then raise exception 'Direct or public team writes allowed';end if;
 reset role;
 update league_private.session_access set slot=1,code_version=(select version from league_private.access_codes where slot=1) where session_id=sid;
 set local role authenticated;
 if not public.can_upload_ssl_logo(logo) or public.can_upload_ssl_logo('2/'||gen_random_uuid()::text||'.png') or public.can_upload_ssl_logo('../1/test.svg') then raise exception 'Logo paths or slot restrictions broken';end if;
 select * into team from public.save_ssl_team(1,'Renamed Pirates '||u::text,town.id,logo);
 if public.league_session_access()->>'team'<>team.name then raise exception 'GM code did not follow team rename';end if;
 begin perform public.save_ssl_team(2,'Wrong slot',town.id,logo);raise exception 'GM edited another slot';exception when others then if sqlerrm<>'You can only edit your assigned team' then raise;end if;end;
 begin perform public.save_ssl_location(null,'GM location','',true);raise exception 'GM managed locations';exception when others then if sqlerrm<>'Commissioner access required' then raise;end if;end;
 begin insert into storage.objects(bucket_id,name) values('ssl-team-logos','2/'||gen_random_uuid()::text||'.png');raise exception 'Other-slot storage upload allowed';exception when insufficient_privilege then null;end;
 reset role;
 update league_private.session_access set slot=0,code_version=(select version from league_private.access_codes where slot=0) where session_id=sid;
 set local role authenticated;
 perform public.save_ssl_location(town.id,town.name,'Retired test',false);
 begin perform public.save_ssl_team(2,'New retired town team',town.id,logo);raise exception 'Retired location chosen';exception when others then if sqlerrm<>'This location is no longer available' then raise;end if;end;
 select * into team from public.save_ssl_team(1,team.name,town.id,logo);
 reset role;
 update league_private.session_access set slot=1,code_version=(select version from league_private.access_codes where slot=1) where session_id=sid;
 update league_private.access_codes set version=version+1 where slot=1;
 set local role authenticated;
 if public.can_upload_ssl_logo(logo) then raise exception 'Revoked code can upload';end if;
 begin perform public.save_ssl_team(1,'Revoked team',town.id,logo);raise exception 'Revoked code edited team';exception when others then if sqlerrm<>'You can only edit your assigned team' then raise;end if;end;
 reset role;
end $$;
set local role anon;
select count(*) as public_team_rows from public.ssl_teams;
reset role;
rollback;
select 'PASS: public reads, commissioner locations and team submission, GM own-team edits, logo path isolation, rename persistence, retired locations, revoked code rejection; all fixtures rolled back' as result;
