import React, {useEffect,useRef,useState} from 'react'
import {LockKeyhole, Shield, Trophy, Vote} from 'lucide-react'

export function ClosedSeasonRoom({kind}){
 const playoffs=kind==='SSL Playoffs', Icon=playoffs?Trophy:Vote
 return <><div className="page-heading"><span className="eyebrow dark">{playoffs?'THE ROAD TO THE TITLE':'YOUR VOICE. YOUR LEAGUE.'}</span><h1>{kind}</h1></div><section className="panel season-closed"><span className="closed-pill"><LockKeyhole size={15}/> CLOSED</span><Icon size={54}/><h2>{playoffs?'THE POSTSEASON IS COMING':'VOTING OPENS LATER'}</h2><p>{playoffs?'Playoff brackets, matchups, and results will appear when the postseason opens.':'All-Star voting, league votes, and other polls will be held here when voting opens.'}</p><small>{playoffs?'Waiting for the playoff field and schedule.':'No active polls. Voting is currently closed.'}</small></section></>
}
function TeamMark({team}){return team?.logo?<img className="draft-team-logo" src={team.logo} alt={`${team.name} logo`} referrerPolicy="no-referrer"/>:<Shield size={34} aria-hidden="true"/>}
export function SSLDraftRoom({supabase,isCommissioner,players}){
 const [seasons,setSeasons]=useState([]),[selected,setSelected]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[rolling,setRolling]=useState(false),[revealed,setRevealed]=useState(null),[setup,setSetup]=useState(false)
 const [name,setName]=useState(''),[rounds,setRounds]=useState(11),[snake,setSnake]=useState(true),[entries,setEntries]=useState(Array.from({length:10},(_,i)=>({id:`team-${i+1}`,name:'',logo:''}))),[chosen,setChosen]=useState('')
 const timer=useRef(null),mounted=useRef(true),lastDraw=useRef(null)
 const season=seasons.find(s=>s.id===selected)||seasons[0]
 async function load(){if(!supabase)return;const r=await supabase.from('ssl_draft_seasons').select('*').order('created_at',{ascending:false});if(mounted.current){if(r.error)setMessage(r.error.message);else setSeasons(r.data||[])}}
 useEffect(()=>{mounted.current=true;load();const poll=setInterval(load,5000);return()=>{mounted.current=false;clearInterval(poll);clearTimeout(timer.current)}},[])
 useEffect(()=>{setRevealed(null);setRolling(false);clearTimeout(timer.current)},[selected])
 useEffect(()=>{if(!isCommissioner)setSetup(false)},[isCommissioner])
 function updateSeason(data){setSeasons(old=>[data,...old.filter(s=>s.id!==data.id)]);}
 async function create(e){e.preventDefault();setBusy(true);setMessage('');const teams=entries.filter(t=>t.name.trim()).map(t=>({...t,name:t.name.trim(),logo:t.logo.trim()}));const r=await supabase.rpc('create_ssl_season',{season_name:name.trim(),team_entries:teams,draft_rounds:Number(rounds),snake_order:snake});setBusy(false);if(r.error){setMessage(r.error.message);return}updateSeason(r.data);setSelected(r.data.id);setSetup(false);setName('')}
 async function act(operation){setBusy(true);setMessage('');const r=await supabase.rpc('ssl_draft_action',{season:season.id,operation,player:operation==='pick'?Number(chosen):null});if(r.error){setBusy(false);setMessage(r.error.message);return}if(operation==='draw'){setRolling(true);setRevealed(null);timer.current=setTimeout(()=>{if(mounted.current){updateSeason(r.data);setRevealed(r.data.draft_order.at(-1));setRolling(false);setBusy(false)}},2800)}else{updateSeason(r.data);setChosen('');setBusy(false)}}
 const order=season?.draft_order||[],picks=season?.picks||[],count=order.length,round=count?Math.floor(picks.length/count):0,index=count?(season.snake&&round%2===1?count-1-picks.length%count:picks.length%count):0,next=order[index]
 useEffect(()=>{
  if(!season)return
  const prior=lastDraw.current;lastDraw.current={id:season.id,count:order.length}
  if(isCommissioner)return
  if(prior?.id===season.id&&order.length>prior.count){setRolling(true);timer.current=setTimeout(()=>{setRevealed(order.at(-1));setRolling(false)},2800)}else setRevealed(order.at(-1)||null)
 },[season?.id,order.length,isCommissioner])
 const available=players.filter(p=>!picks.some(x=>x.player===p.id))
 return <><div className="page-heading"><span className="eyebrow dark">EVERY SEASON STARTS HERE</span><h1>SSL DRAFT ROOM</h1><p>Season drafts, lottery night, and the official pick order.</p></div>
 <div className="draft-room-toolbar">{seasons.length>0&&<label>SEASON <select value={season.id} disabled={busy} onChange={e=>setSelected(e.target.value)}>{seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}{isCommissioner&&<button className="outline-btn" disabled={busy} onClick={()=>setSetup(!setup)}>{setup?'CLOSE SETUP':'SET UP A SEASON'}</button>}</div>
 {setup&&isCommissioner&&<form className="panel season-draft-setup" onSubmit={create}><h2>NEW SEASON</h2><p>Add the official teams and logo URLs. Blank rows are skipped. Test teams are kept separate.</p><div className="draft-setup-fields"><label>SEASON NAME<input required minLength={2} maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><label>ROUNDS<input type="number" min={1} max={20} required value={rounds} onChange={e=>setRounds(e.target.value)}/></label><label>DRAFT FORMAT<select value={snake?'snake':'straight'} onChange={e=>setSnake(e.target.value==='snake')}><option value="snake">Snake (reverses each round)</option><option value="straight">Straight (same order each round)</option></select></label></div><div className="draft-team-fields">{entries.map((t,i)=><div key={t.id}><input aria-label={`Team ${i+1} name`} placeholder={`Team ${i+1} name`} maxLength={80} value={t.name} onChange={e=>setEntries(old=>old.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><input aria-label={`Team ${i+1} logo URL`} type="url" placeholder="https://… team logo (optional)" maxLength={500} value={t.logo} onChange={e=>setEntries(old=>old.map((x,j)=>j===i?{...x,logo:e.target.value}:x))}/></div>)}</div><button className="red-btn" disabled={busy||entries.filter(t=>t.name.trim()).length<2}>CREATE SEASON & SAVE LOTTERY</button><p className="setup-note">The randomized order is saved once. Each draw reveals the next team; refreshing does not reroll it. Draft picks are recorded by the commissioner.</p></form>}
 <section className="panel lottery-panel"><div className="section-title"><div><small>{season?.name||'LOTTERY NIGHT'}</small><h2>DRAFT LOTTERY</h2></div><span className="closed-pill">{season?season.stage.toUpperCase():'NOT SCHEDULED'}</span></div><div className="lottery-stage"><div className={`bingo-machine ${rolling?'rolling':''}`} aria-hidden="true"><div className="bingo-cage">{Array.from({length:9},(_,i)=><span key={i} className={`bingo-small-ball ball-${i}`}>{i+1}</span>)}<div className="cage-ribs"/></div><div className="bingo-base">SSL LOTTERY</div><div className="bingo-chute"/></div><div className={`lottery-result ${rolling?'rolling':''}`} aria-live="polite"><div className="lottery-ball">{rolling?'?':revealed?<TeamMark team={revealed}/>:<span>SSL</span>}</div><small>{rolling?'THE BALL IS ROLLING…':revealed?`PICK ${order.length}`:'THE NEXT PICK'}</small><h3>{rolling?'WHO’S UP NEXT?':revealed?.name||'WAITING FOR LOTTERY NIGHT'}</h3>{revealed?.logo&&<span className="setup-note">Official team logo</span>}</div></div><div className="lottery-controls"><p>{!season?'The commissioner will set up the first season and its participating teams.':season.stage==='lottery'?`${order.length} of ${season.teams.length} teams revealed. Each team has an equal chance at each remaining position.`:'Lottery complete. The saved order is shown below.'}</p>{isCommissioner&&season?.stage==='lottery'&&<button className="yellow-btn" disabled={busy} onClick={()=>act('draw')}>{rolling?'ROLLING…':'ROLL NEXT BINGO BALL'}</button>}{isCommissioner&&season?.stage==='ready'&&<button className="red-btn" disabled={busy} onClick={()=>act('start')}>OPEN SEASON DRAFT</button>}</div></section>
 {order.length>0&&<section className="panel"><div className="section-title"><h2>OFFICIAL DRAFT ORDER</h2></div><ol className="draft-order-list">{order.map((t,i)=><li key={t.id}><strong>#{i+1}</strong><TeamMark team={t}/><span>{t.name}</span></li>)}</ol></section>}
 {season&&['drafting','complete'].includes(season.stage)&&<section className="panel"><div className="section-title"><div><small>{season.snake?'SNAKE DRAFT':'STRAIGHT DRAFT'} · {season.rounds} ROUNDS</small><h2>{season.stage==='complete'?'DRAFT COMPLETE':`ON THE CLOCK: ${next?.name}`}</h2></div></div>{season.stage==='drafting'&&<div className="season-pick-controls"><p>Round {round+1} · Pick {picks.length+1} of {season.teams.length*season.rounds}</p>{isCommissioner?<><select aria-label="Player to draft" value={chosen} onChange={e=>setChosen(e.target.value)}><option value="">Choose a player</option>{available.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="red-btn" disabled={busy||!chosen} onClick={()=>act('pick')}>RECORD PICK</button></>:<p>The commissioner records the picks as teams draft.</p>}</div>}<div className="table-scroll"><table><thead><tr><th>Pick</th><th>Round</th><th>Team</th><th>Player</th></tr></thead><tbody>{picks.map(p=><tr key={p.number}><td>{p.number}</td><td>{p.round}</td><td>{season.teams.find(t=>t.id===p.team)?.name}</td><td>{players.find(x=>x.id===p.player)?.name}</td></tr>)}</tbody></table></div></section>}
 {message&&<p className="inline-message" role="status">{message}</p>}
 </>
}
